uploads = []
generated = []

[[outputs]]
id = "o2pNimo0gD40jdUUVNPQN"
uri = "file://nft-platform.zip"
type = "unspecified"
title = "nft-platform.html — Complete Standalone File (User + Admin)"

[[outputs]]
id = "2LQSP2_KOCOdeiVUAfMjf"
uri = "file://nft-platform-full-backup.zip"
type = "unspecified"
title = "THE SUPER NFT — Full Backup (29.75 MB)"
